def handle_error(prefix):
    exc_format = ' '.join(traceback.format_exception(*sys.exc_info()))
    ...